name = "mohamad"
main = "./src/index.js"
compatibility_date = "2026-09-14"

# تنظیمات دایرکتوری فایل‌های استاتیک (سایت)
[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-app"
