name = "mohamad"
main = "./src/index.js"
compatibility_date = "2026-09-14"

# کلید اصلی برای رفع خطای سیستم Build خودکار Cloudflare Pages
pages_build_output_dir = "./public"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]
